### PR TITLE
Added optional HTTPS, togglable with the idp.json config "useHttps"

### PR DESCRIPTION
**Pull request by Martini991**

### CODE REVIEW

**Comment by damikael** [comment]
Hello @Martini991,
HTTPS in not related to the value of entityID. Infact The value of entityID can also  be different from an URL.
Furthermore HTTPS can be achieved through reverse proxy instead of start app directly on HTTPS.
However the choice to start app on HTTPS could be defined in configuration.
Can you change to load it from idp.json? 
Thanks

**Comment by Martini991** [comment]
@damikael done! 👍🏻 
Look if the changes are now complaint with your comment.

> Hello @Martini991,
> HTTPS in not related to the value of entityID. Infact The value of entityID can also be different from an URL.
> Furthermore HTTPS can be achieved through reverse proxy instead of start app directly on HTTPS.
> However the choice to start app on HTTPS could be defined in configuration.
> Can you change to load it from idp.json?
> Thanks

**Comment by fume** [comment]
> Hello @Martini991,
> HTTPS in not related to the value of entityID. Infact The value of entityID can also be different from an URL.
> Furthermore HTTPS can be achieved through reverse proxy instead of start app directly on HTTPS.
> However the choice to start app on HTTPS could be defined in configuration.
> Can you change to load it from idp.json?
> Thanks

hi @damikael ,
as you said, entityID is an URI, not an URL. So why the spid-saml-check tool checks for an HTTPS entityID? There is no AGID rule asking for the entityID to be https, and even if there is one, it makes completely no sense at all. Please refer to #114 

thanks, regards

**Comment by Martini991** [comment]
@damikael, the gentlest of bumps on this. Can the PR be merged now? Need more edits? Let me know, thanks! 😄

**Pull request merged**
